version: '3'
services:
  authentication:
    container_name: authentication-container
    build: ./authentication
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8001:8000
    volumes:
      - ./authentication:/usr/code/app
    environment:
      - DATABASE_URL=postgres://postgres:postgres@database:5432/awsws_authentication
    depends_on:
      - database
    restart: always

  inventory:
    container_name: inventory-container
    build: ./inventory
    command:
      - /bin/bash
      - -c
      - |
        uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
        cd /code/app && PYTHONPATH="/code" python3 consumer.py
    ports:
      - 8002:8000
    volumes:
      - ./inventory:/usr/code/app
    environment:
      - DATABASE_URL=postgres://postgres:postgres@database:5432/awsws_inventory
    depends_on:
      - database
    restart: always

  payment:
    container_name: payment-container
    build: ./payment
    command:
      - /bin/bash
      - -c
      - |
        uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
        cd /code/app && PYTHONPATH="/code" python3 consumer.py
    ports:
      - 8003:8000
    volumes:
      - ./payment:/usr/code/app
    environment:
      - DATABASE_URL=postgres://postgres:postgres@database:5432/awsws_payment
    depends_on:
      - database
    restart: always

  database:
    container_name: database-container
    build: ./database
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
